/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\vedant\OneDrive\Desktop\Mediterate\public\models\radio.glb --draco 
Author: TraianDumbrava (https://sketchfab.com/TraianDumbrava)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/radio-d21d6bf783154170bfa6dc7ce0a208f1
Title: Radio
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Radio(props) {
  const { nodes, materials } = useGLTF('/models/radio.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI, 0]}>
      <group position={[0, 115.687, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.981, 0.621, 1]}>
        <mesh geometry={nodes['Radio_20_-_Default_0'].geometry} material={materials['20_-_Default']} position={[0, 0, -115.687]} />
      </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/radio.glb')
